name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # (Optional) Let Dependabot or you keep Node      ↑
      #            in package.json; Oryx will respect it.
      #            No setup-node step is required here.

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_OCEAN_0BC19E51E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload

          # ==== build/deploy paths ====
          app_location: "chatbot" # front-end source
          api_location: "api" # Functions source
          output_location: "dist" # built SPA inside /chatbot/dist
          config_file_location: "./staticwebapp.config.json" # <-- new
          # ============================

        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_OCEAN_0BC19E51E }}
          action: close
